bin.includes = META-INF/,\
               plugin_zh_CN.properties,\
               org.opengroup.archimate.xmlexchange.zh_CN.jar
jars.compile.order = org.opengroup.archimate.xmlexchange.zh_CN.jar
source.org.opengroup.archimate.xmlexchange.zh_CN.jar = src/
output.org.opengroup.archimate.xmlexchange.zh_CN.jar = bin/
