bin.includes = META-INF/,\
               plugin_zh_CN.properties,\
               nl/,\
               com.archimatetool.templates.zh_CN.jar
jars.compile.order = com.archimatetool.templates.zh_CN.jar
source.com.archimatetool.templates.zh_CN.jar = src/
output.com.archimatetool.templates.zh_CN.jar = bin/
