bin.includes = META-INF/,\
               plugin_zh_CN.properties,\
               com.archimatetool.modelimporter.zh_CN.jar
jars.compile.order = com.archimatetool.modelimporter.zh_CN.jar
source.com.archimatetool.modelimporter.zh_CN.jar = src/
output.com.archimatetool.modelimporter.zh_CN.jar = bin/
