bin.includes = META-INF/,\
               about_zh_CN.properties,\
               plugin_zh_CN.properties,\
               org.eclipse.gef.zh_CN.jar
jars.compile.order = org.eclipse.gef.zh_CN.jar
source.org.eclipse.gef.zh_CN.jar = src/
output.org.eclipse.gef.zh_CN.jar = bin/
