bin.includes = META-INF/,\
               plugin.xml,\
               plugin.properties,\
               com.archimatetool.mcp.jar
jars.compile.order = com.archimatetool.mcp.jar
source.com.archimatetool.mcp.jar = src/
output.com.archimatetool.mcp.jar = bin/
